=== DAL225/40260/xml/xml-00.dtd
<?xml version="1.0" enconding="UTF-8"?>
<!ELEMENT dirección (nombreCompleto, correo, teléfono, cumple)>
<!ELEMENT nombreCompleto (nombre, apellido)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT correo (#PCDATA)>
<!ELEMENT teléfono (#PCDATA)>
<!ELEMENT cumple (dia, mes, anio)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT anio (#PCDATA)>

=== DAL225/40260/xml/xml-00.xml
<?xml version="1.0" enconding="UTF-8"?>
<!DOCTYPE dirección SYSTEM "xml-00.dtd">
<dirección>
    <nombreCompleto>
        <nombre>
            Diego
        </nombre>
        <apellido>
            Aburto
        </apellido>
    </nombreCompleto>
    <correo>diego@gmail.com</correo>
    <teléfono>911</teléfono>
    <cumple>
        <dia>25</dia>
        <mes>02</mes>
        <anio>2006</anio>
    </cumple>
</dirección>
